export const ROOT = '/'
export const DASHBOARD = '/dashboard'
export const DASHBOARD_DISCUSSION = '/dashboard/discussion'
export const ADMIN_USERS = '/admin/users'
export const ADMIN_DISCUSSIONS = '/admin/discussions'
